# -*- coding: utf-8 -*-
# ---------------------------------------------------------------------------
# batchclip.py
# Created on: 2013-10-16 22:03:35.00000
#   (generated by ArcGIS/ModelBuilder)
# Description: 
# ---------------------------------------------------------------------------

# Import arcpy module
import arcpy
import os

# Check out any necessary licenses
arcpy.CheckOutExtension("spatial")

# get work directory
#folderPath=os.getcwd()
#arcpy.AddMessage(folderPath)

# Local variables:
# arcpy.GetParameterAsText
plotFeatureLayer=arcpy.GetParameterAsText(0)
rasterLayer=arcpy.GetParameterAsText(1)
outputFolder=arcpy.GetParameterAsText(2)+"\\"

arcpy.AddMessage(outputFolder)
#cancel selection
arcpy.SelectLayerByAttribute_management(plotFeatureLayer, "CLEAR_SELECTION")
arcpy.SelectLayerByAttribute_management (plotFeatureLayer, "NEW_SELECTION", "")

# get plot number
plotNum=int(arcpy.GetCount_management(plotFeatureLayer).getOutput(0))
arcpy.AddMessage("In total "+str(plotNum)+" plots to clip the raster layer")
arcpy.AddMessage("start clipping process")

rows = arcpy.SearchCursor(plotFeatureLayer)

for row in rows:
	arcpy.AddMessage("record:"+str(row.FID))
	# Process: Select Layer By Attribute
	arcpy.SelectLayerByAttribute_management(plotFeatureLayer, "NEW_SELECTION", "\"FID\" ="+str(row.FID))
	# Process: Extract by Mask
	outputName=outputFolder+rasterLayer+"_"+str(row.FID)+".tif"
	arcpy.gp.ExtractByMask_sa(rasterLayer, plotFeatureLayer, outputName)
	
# Process: Select Layer By Attribute
#arcpy.SelectLayerByAttribute_management(Parcels_08_2013, "NEW_SELECTION", "\"OBJECTID\" =2")

# Process: Extract by Mask
#arcpy.gp.ExtractByMask_sa(Raster_Layer, Parcels_08_2013__2_, Output_raster)

